//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/DemoAssets/DemoActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DemoActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DemoActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DemoActions"",
    ""maps"": [
        {
            ""name"": ""Swimming"",
            ""id"": ""f63eba51-340f-4582-b1f9-f0726efff31c"",
            ""actions"": [
                {
                    ""name"": ""PointerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""f5e79b55-0a7a-4e93-a06e-ecf754878fee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwimForward"",
                    ""type"": ""Button"",
                    ""id"": ""825cc1c2-0cbe-4a7f-b439-2559ce0dc6b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""df2f54aa-dd76-4078-a04e-ba77a3db5791"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6dc5f829-e30c-4d8a-a788-4ed05c219665"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwimForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Swimming
        m_Swimming = asset.FindActionMap("Swimming", throwIfNotFound: true);
        m_Swimming_PointerPosition = m_Swimming.FindAction("PointerPosition", throwIfNotFound: true);
        m_Swimming_SwimForward = m_Swimming.FindAction("SwimForward", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Swimming
    private readonly InputActionMap m_Swimming;
    private List<ISwimmingActions> m_SwimmingActionsCallbackInterfaces = new List<ISwimmingActions>();
    private readonly InputAction m_Swimming_PointerPosition;
    private readonly InputAction m_Swimming_SwimForward;
    public struct SwimmingActions
    {
        private @DemoActions m_Wrapper;
        public SwimmingActions(@DemoActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PointerPosition => m_Wrapper.m_Swimming_PointerPosition;
        public InputAction @SwimForward => m_Wrapper.m_Swimming_SwimForward;
        public InputActionMap Get() { return m_Wrapper.m_Swimming; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SwimmingActions set) { return set.Get(); }
        public void AddCallbacks(ISwimmingActions instance)
        {
            if (instance == null || m_Wrapper.m_SwimmingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SwimmingActionsCallbackInterfaces.Add(instance);
            @PointerPosition.started += instance.OnPointerPosition;
            @PointerPosition.performed += instance.OnPointerPosition;
            @PointerPosition.canceled += instance.OnPointerPosition;
            @SwimForward.started += instance.OnSwimForward;
            @SwimForward.performed += instance.OnSwimForward;
            @SwimForward.canceled += instance.OnSwimForward;
        }

        private void UnregisterCallbacks(ISwimmingActions instance)
        {
            @PointerPosition.started -= instance.OnPointerPosition;
            @PointerPosition.performed -= instance.OnPointerPosition;
            @PointerPosition.canceled -= instance.OnPointerPosition;
            @SwimForward.started -= instance.OnSwimForward;
            @SwimForward.performed -= instance.OnSwimForward;
            @SwimForward.canceled -= instance.OnSwimForward;
        }

        public void RemoveCallbacks(ISwimmingActions instance)
        {
            if (m_Wrapper.m_SwimmingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISwimmingActions instance)
        {
            foreach (var item in m_Wrapper.m_SwimmingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SwimmingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SwimmingActions @Swimming => new SwimmingActions(this);
    public interface ISwimmingActions
    {
        void OnPointerPosition(InputAction.CallbackContext context);
        void OnSwimForward(InputAction.CallbackContext context);
    }
}
